name: Testing

on:

  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
  
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy Gcloud
        run : |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/flask-fire
          cd server
          gcloud beta run deploy --image gcr.io/${{ secrets.PROJECT_ID }}/flask-fire
          
