name: Deploy

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  gcloud:
  
    name: gcloud setup + deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: 'Setup auth Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
        
      - name: GCloud build
        run: |
          cd server
          gcloud builds submit \
            --quiet \
            --tag gcr.io/flask-gcloud-xxxx/flask-gcloud
          
      - name: GCloud deploy
        run: |
          gcloud --quiet beta run deploy flask-gcloud \
            --image gcr.io/flask-gcloud-xxxx/flask-gcloud \
            --region europe-west1
          cd ..
          
  firebase:
  
    name: firebase setup + deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
                  
      - name: Firebase install
        run: npm install -g firebase-tools
        
      - name: Deploy firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
