name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
  
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: 'Setup auth Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
        
      - name: GCloud build
        run: |
          cd server
          gcloud builds submit \
            --quiet \
            --tag gcr.io/flask-gcloud-xxxx/flask-gcloud
          
      - name: GCloud deploy
        run: |
          gcloud --quiet beta run deploy flask-fire2 \
            --image gcr.io/flask-gcloud-xxxx/flask-gcloud \
            --region europe-west1
          cd ..
            
      - name: Firebase install
        run: npm install -g firebase-tools
        
      - name: Deploy firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
