name: Testing

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
  
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_email: studiogalactik@gmail.com
          project_id: flask-gcloud-xxxx
      
      - name: Deploy Gcloud
        run: |
          cd server
          gcloud builds submit --tag gcr.io/flask-gcloud-xxxx/flask-gcloud
          gcloud beta run deploy --image gcr.io/flask-gcloud-xxxx/flask-gcloud
          cd ..
      
      - name: Firebase install
        run: npm install firebase-tools
        
      - name: Deploy firebase
        run: firebase deploy
