name: Testing

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
  
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: 'Setup auth Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
        
      - name: GCloud build
        run: |-
          cd server \
          gcloud builds submit \
            --quiet \
            --tag gcr.io/flask-gcloud-xxxx/flask-gcloud
          
          cd ..
      - name: GCloud deploy
        run: |-
          gcloud beta run deploy \
            --quiet \
            --image gcr.io/flask-gcloud-xxxx/flask-gcloud
            
      - name: Firebase install
        run: npm install firebase-tools
        
      - name: Deploy firebase
        run: firebase deploy
